### ISSUE TITLE
9 - Nginx - Reverse Proxy Cofigurations

### ISSUE THREAD

**Issue by ThinhPhan** [ThinhPhan/notes#9]
Setup Odoo run behind Nginx as a Reverse Proxy at default path (/) on port 8080  - everything is containerized.

Got weird issue

## Actual behavior
Run at `localhost:8080` -> will get redirected to `localhost/web` and show page is not found

## Expected behavior
- Show Odoo login page `localhost:8080/web/login`

## Investigate

- Check with `curl`
`curl --head http://localhost:8080` will show `303 See Other` redirect to `/web` and at `/web` required authentication but seem like Nginx cannot redirect properly to `/web/login`

```sh
HTTP/1.1 303 SEE OTHER
Server: nginx/1.27.0
Date: Thu, 27 Jun 2024 04:45:17 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 214
Location: http://localhost/web
Connection: keep-alive
Set-Cookie: session_id=xxx; Expires=Fri, 27 Jun 2025 04:45:17 GMT; Max-Age=604800; HttpOnly; Path=/
X-Content-Type-Options: nosniff
```

- Follow redirect `curl -L http://localhost:8080` will render login page of Odoo.

- If run with trailing slash `localhost:8080/web/`, it works fine!.

## How to reproduce?

Nginx reverse proxy configuration and Dockerfile
- default.conf

```conf
server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location / {
      proxy_redirect off;
      proxy_pass http://odoo:8069;
     
      proxy_set_header Host $host; # to forward the original host requested by the client
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-For $proxy_protocol_addr;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Real-IP $remote_addr;
    }
```

```yml
version: '3'
services:
    odoo:
        image: odoo:latest
        env_file: .env
        restart: always
        volumes:
            - ./addons:/mnt/extra-addons/:rw
            - ./config/odoo:/etc/odoo/:rw
            - ./odoo-web-data:/var/lib/odoo/:rw
        ports:
            - "8069:8069"
        depends_on:
            - db
        networks:
          - odoo_network
    nginx:
        container_name: nginx
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 8080:80
            - 443:443
        volumes:
            - ./config/nginx/conf:/etc/nginx/conf.d/:rw
        depends_on:
            - "odoo"
        networks:
            - odoo_network
    db:
      image: postgres:15
      restart: always # run as a service
      env_file: .env
      ports:
        - "5432:5432"
      volumes:
        - ./odoo-db-data:/var/lib/postgresql/data/pgdata
      networks:
        - odoo_network
        
networks:
  odoo_network:
    driver: bridge

volumes:
  odoo-web-data:
  odoo-db-data:
```

## Solution

The response from the proxy should contains Forwarded header, which points to the proxy. By setting X-Forwarded-Host and Host. The difference here is the values of `$http_host` and `$host`. Most of the guides on internet use `$host` which is not working. So the correct setup is

```conf
location / {
        proxy_redirect off;
        proxy_pass http://odoo:8069; 

        # Add Headers for odoo proxy mode
        proxy_set_header Host **$http_host**; # to forward the original host requested by the client
        proxy_set_header X-Forwarded-Host **$http_host**;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
    }
```

## Further Reading
- [ ] What is the difference between `$http_host` and `$host`? Why is it have this behavior? 

## References

- [StackOverflow - 303 cache is preventing headers from being sent](https://stackoverflow.com/questions/72982093/303-cache-is-preventing-headers-from-being-sent)
- [HTTP Redirect 303 to wrong URL (in case port is not 80) when trailing slash is not added](https://github.com/keycloak/keycloak/issues/14581)
